In [8]:
# 연습 문제 1

import numpy as np

np.random.seed(0)  # seed 0 설정

rolls = np.random.randint(1, 7, size=100)  # 주사위를 100번 던진 결과 생성

rolls_mean = np.mean(rolls) # 주사위를 100번 던져서 나온 숫자들의 평균 계산

rolls_mean

3.42

In [16]:
# 연습 문제 2

a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])

b = a1 + a2

b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [21]:
# 연습 문제 3

# 1부터 9까지의 정수 값을 갖는 1차원 ndarray 생성
a = np.arange(1,10)

# 3부터 27까지의 3의 배수를 갖는 ndarray 출력
b = a * 3

b

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [22]:
# 연습 문제 4

a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [36]:
# 연습 문제 5

a = np.arange(50)

a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [39]:
# 연습 문제 6

a = np.empty((3,3,3) , dtype = '<U10') # 3x3x3 배열을 갖고, 최대 10글자 출력

a

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [44]:
# 연습 문제 6 해설

a = np.zeros((3,3,3) , dtype = '<U10')

a

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [45]:
# 연습 문제 7

a = np.full((3, 3, 3), "playdata", dtype = '<U10')

a

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U10')

In [55]:
# 연습 문제 8

# 1부터 40까지의 짝수를갖는 1차원 ndarray 생성 후 (2, 2, 5)으로 shape변경
a = np.arange(2, 41, 2).reshape(2, 2, 5) 
a

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [57]:
# 단위 행렬 만들기
# 정사각
# 기본 타입 float
# dtype 인수를 이용해 타입 변경 가능


In [56]:
# 단위 행렬 만들기

# 연습 문제 9


matrix = np.eye(4, dtype = int) # 4X4 크기의 정수 타입 단위 행렬 생성
matrix


# matrix = np.identity(4, dtype=int) # 4X4 크기의 정수 타입 단위 행렬 생성
# matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# 넘파이 배열 데이터 타입 변경하기
# astype() 메서드 사용

ndarray.astype(dtype, order~~~~~


In [60]:
a = np.ones((2, 3, 2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [63]:
a.astype("i")

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [68]:
# 넘파이 배열 데이터 타입 변경하기

# 연습 문제 10

np.random.seed(0) # seed 0으로 설정


# 0과 1을 랜덤하게 9개 갖는 1차원 ndarray 생성
a = np.random.randint(0, 2, 9)


# 데이터 타입을 bool로 변경하고 모양을 (3,3)으로 변경
a.astype("bool").reshape(3, 3)



array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [74]:
# 연습 문제 11

np.random.seed(0)  # seed 0으로 설정

a = np.random.rand(10) # 0과 1사이의 실수 10개를 갖는 1차원 ndarray 생성

b = (a * 10).astype(int) # 요소에 각 10을 곱하고 데이터타입 int로 변경

b

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3])

In [88]:
# 연습 문제 12

a = np.ones((10, 10))   # 10 x 10 행렬생성

a[1:-1, 1:-1] = 0   # 슬라이싱을 사용해 테두리를 제외한 안쪽 값을 0으로 변경

a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [103]:
a = np.ones((10, 10)) 
a[1:9, 1:9] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [105]:
# 연습 문제 13

a = np.zeros((10, 10))   

a[1:-1, 1:-1] = 1   

a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [128]:
# 연습 문제 13

a = np.ones((10, 10)) 

a[0,:] = 0    # 첫 번째 행을 0으로 할당
a[-1:] = 0    # 마지막 행을 0으로 할당
a[:,0] = 0    # 첫 번째 열을 0으로 할당
a[:,-1] = 0   # 마지막 열을 0으로 할당

a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [129]:
# 연습 문제 13 강사님 풀이

a = np.ones((10, 10)) 

a[ : , [0,-1]] = 0

a[[0,-1] , : ] = 0

print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [175]:
# 연습 문제 14

a = np.ones((8,8))

a[::2, 1::2] = 0  # 홀수 행의 짝수 열 요소를 0으로 변경
a[1::2, ::2] = 0  # 짝수 행의 홀수 열 요소를 0으로 변경

print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [176]:
# 연습 문제 14 강사님 풀이

a = np.ones((8,8))

a[1::2, ::2] = 0  # 짝수 행의 홀수 열 요소를 0으로 변경
a[::2, 1::2] = 0  # 홀수 행의 짝수 열 요소를 0으로 변경

print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [177]:
# 연습 문제 14 이건 반대네

# 0로 채워진 8x8 배열 생성
a = np.ones((8, 8))

# 짝수 번째 행과 열의 요소를 1으로 변경
a[::2, ::2] = 0  # 첫 번째 행, 세 번째 행, ...의 첫 번째 열, 세 번째 열, ... 
a[1::2, 1::2] = 0  # 두 번째 행, 네 번째 행, ...의 두 번째 열, 네 번째 열, ...

# 배열 출력
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [185]:
# 연습 문제 15

a = np.array([[1, 0], [0, 1]])

b = np.eye(, dtype = int )



TypeError: only integer scalar arrays can be converted to a scalar index

In [190]:
np.tile(np.eye(2), (4, 4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [191]:
# boolean indexing

a = np.arange(1, 5)
print(a)

[1 2 3 4]


In [193]:
even = np.array([True if i%2 == 0 else False for i in range(1, 5)])
print(even)

[False  True False  True]


In [194]:
a[even]

array([2, 4])

In [202]:
# 연습 문제

a = np.arange(11)

a[(a > 3) & ( a < 7 )] *= -1    # 3 초과 7 미만인 숫자를 음수로 변경

print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [234]:
# True if 어케써

a = np.arange(11)

b = np.array([True if 3 < i < 7 *= -1 else False for i in range(11)])

print(b)

SyntaxError: invalid syntax (917391436.py, line 5)

In [9]:
# 연습 문제 
# 1부터 100까지의 3의 배수를 갖는 1차원 ndarray를 생성하고 그 전체의 합을 구하세요.

a = np.arange(1, 101) # 1부터 100까지의 정수 생성


b = a[a % 3 == 0] # 3의 배수만 선택

sum = np.sum(b) # 전체 합

print(sum)


1683


In [287]:
# 연습 문제
# linspace()를 활용하여 다음과 같은 1차원 ndarray를 만들어보세요

a = np.linspace(0.1, 0.9, 9)

print(a)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
# 연습 문제

 #1~45 중 중복 없이 6개 숫자 추출
    # 복원추출 replace = True, 비복원 추출 replace = False
    
while True:
    try:
        num = int(input("로또 번호를 몇 개 생성하시겠습니까? "))
        if num <= 0:
            raise ValueError("자연수만 입력해주세요.")
        break
    except ValueError as e:
        print(e)


for i in range(num):
    lotto_numbers.append(np.sort(np.random.choice(range(1, 46), size=6, replace=False)))


numbers

In [285]:

while True:
    try:
        num = int(input("로또 번호를 몇 개 생성하시겠습니까? "))
        if num <= 0:
            raise ValueError("자연수만 입력해주세요.")
        break
    except ValueError as e:
        print(e)

lotto_numbers = np.sort(np.random.choice(range(1, 46), size=6, replace=False))


print("로또 번호 생성 결과:")
for numbers in lotto_numbers:
    print(numbers)

로또 번호를 몇 개 생성하시겠습니까?  5


로또 번호 생성 결과:
1
12
18
26
28
38


In [289]:
# 기영님 풀이

while True:
    n = input("자연수를 입력해주세요.")
    try:
        for i in range(int(n)):
            k = np.array([np.random.choice(np.arange(46), replace=False) for _ in range(6)])
            print(np.sort(k))
        break;
    except ValueError:
        print("자연수를 입력해주세요.")

자연수를 입력해주세요. 5


[ 1  4  5 23 34 35]
[16 26 34 37 44 45]
[ 4  5  6  9 25 31]
[ 2  6 11 12 17 19]
[10 20 23 25 35 44]


In [274]:
lotto_numbers = []
for i in range(num):
    lotto_numbers.append(np.sort(np.random.choice(range(1, 46), size=6, replace=False)))

print("로또 번호 생성 결과:")
for numbers in lotto_numbers:
    print(numbers)


로또 번호 생성 결과:
[ 1  7 19 32 33 35]
[ 8 13 28 32 35 36]
[10 22 26 28 31 43]
[ 4 21 22 35 39 40]
[ 6 10 15 27 32 34]
[ 8 10 13 21 30 31]


In [280]:
def make_lotto(count):
    for i in range(count):
    lotto_num = [] # 로또 번호가 담길 리스트형 변수

    for j in range(6): # 6번 반복
        lotto_num = np.random.choice(range(1,46),6,replace=False)
        
    lotto_num.sort() # 값 정렬
    print("{}. 로또번호: {}".format(i+1, lotto_num))


count = int(input("로또 번호를 몇개 생성할까요?> "))
make_lotto(count)

IndentationError: expected an indented block (4236348581.py, line 3)

In [8]:
# 강사님 풀이

import numpy as np

while True:
    try:
        count = int(input("로또 번호를 몇 개 생성하시겠습니까? "))
        if count <= 0:
            raise Error
        numbers = np.arange(1, 46)
        lottos = [np.sort(np.random.choice(numbers, 6,replace=False)) for _ in range(count)]
        display(lottos) # 예쁘게 보여주기위한거
        break
    except ValueError :
        print("자연수만 입력해주세요.")
        
        

로또 번호를 몇 개 생성하시겠습니까?  6


[array([13, 17, 22, 34, 39, 43]),
 array([ 1, 16, 17, 20, 30, 44]),
 array([ 1,  4, 13, 22, 42, 44]),
 array([ 3,  5, 23, 27, 36, 37]),
 array([13, 25, 27, 34, 37, 41]),
 array([ 2, 12, 13, 22, 30, 39])]

In [13]:
# 연습 문제  
# for 반복문 사용

resp_time = np.array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
                      199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
                      177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
                      168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
                      55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
                      49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
                      186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
                      199, 55, 151, 183, 152, 119, 193, 110, 204])

count = 0
for i in resp_time:
    if i > 200:
        count += 1

print(count)


8


In [15]:
# 연습 문제  
# len 함수 사용

resp_time = np.array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
                      199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
                      177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
                      168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
                      55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
                      49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
                      186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
                      199, 55, 151, 183, 152, 119, 193, 110, 204])

len(resp_time[resp_time>200])



8

In [16]:
# 연습 문제 강사님 풀이

resp_time = np.array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
                      199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
                      177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
                      168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
                      55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
                      49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
                      186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
                      199, 55, 151, 183, 152, 119, 193, 110, 204])


(resp_time > 200).sum()


8

In [20]:
import numpy as np

resp_time = np.array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
                      199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
                      177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
                      168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
                      55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
                      49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
                      186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
                      199, 55, 151, 183, 152, 119, 193, 110, 204])

s = np.sort(resp_time)  # 데이터를 오름차순으로 정렬
a = np.percentile(sorted_resp_time, 25)  # 제1사분위수 계산
b = np.percentile(sorted_resp_time, 50)   # 제2사분위수 계산
c = np.percentile(sorted_resp_time, 75)  # 제3사분위수 계산

print("a:", a)
print("b:", b)
print("c:", c)


a: 71.5
b: 131.0
c: 175.5


In [27]:
# 진명님코드
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])

a25 = len(result[np.where(result == 0)])
a26 = len(result[np.where(result == 1)])
a27 = len(result[np.where(result == 2)])

a28 = np.array([a25, a26, a27])
a29 = np.bincount(result)
a30 = np.argmax(a28)



print(f"{p[a29.argmax()]}가 {a29.max()}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [45]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])

a = np.bincount(result)
b = a.argmax()

print(f"{p[b]}가 {a.max()}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [47]:
 # 강사님 풀이
    
count = np.bincount(result, minlength = 3)
winner_index = count.argmax()
print(f"{p[winner_index]}가 {count[winner_index]}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [ ]:
vote_count = np.zeros(3)

for i in result:
    vote_count[i] += 1

for i in range(len(p)):
    print(f"{p[i]} 후보가 {vote_count[i]}표를 
