In [2]:
import numpy as np

In [3]:
x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [4]:
x.min()

0

In [5]:
np.min(x)

0

In [6]:
# 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있습니다.

x.min(axis = 0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
np.min(x, axis = 1)

array([[ 0,  1],
       [10, 11]])

In [8]:
x.min(axis = 2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [12]:
# argmin() 메서드는 해당 배열의 제일 작은 값의 인덱스를 반환합니다. 

x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [13]:
x.argmin()

0

In [14]:
np.argmin(x)

0

In [15]:
# 연산 대상이 2차원이상일 때에는 axis 키워드 인수를 사용할 수 있습니다.

x.argmin(axis = 0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [16]:
np.argmin(x, axis = 1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [17]:
x.argmin(axis = 2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [18]:
# max() 메서드는 해당 배열의 제일 큰 값의 결과를 반환합니다.

x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [19]:
x.max()

19

In [20]:
np.max(x)

19

In [21]:
# 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있습니다.

x.max(axis = 0)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [22]:
np.max(x, axis = 1)

array([[ 8,  9],
       [18, 19]])

In [23]:
x.max(axis = 2)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [24]:
# argmax() 메서드는 해당 배열의 제일 큰 값의 인덱스를 반환합니다.

x = np.arange(20).reshape(2, 5, -1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [25]:
x.argmax()

19

In [26]:
np.argmax(x)

19

In [27]:
# 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있습니다.

x.argmax(axis = 0)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [28]:
np.argmax(x, axis = 1)

array([[4, 4],
       [4, 4]], dtype=int64)

In [29]:
x.argmax(axis = 2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [38]:
# 강사님 예

import numpy as np
import random
test = np.array([random.randint(1, 99) for _ in range(20)]).reshape(2, 5, -1)
test

array([[[37, 78],
        [ 4, 62],
        [49, 75],
        [14, 66],
        [75, 46]],

       [[90, 82],
        [74, 32],
        [82, 87],
        [49, 17],
        [70, 33]]])

In [39]:
np.min(test, axis = 0)

array([[37, 78],
       [ 4, 32],
       [49, 75],
       [14, 17],
       [70, 33]])

In [40]:
np.min(test, axis = 1)

array([[ 4, 46],
       [49, 17]])

In [41]:
np.min(test, axis = 2)

array([[37,  4, 49, 14, 46],
       [82, 32, 82, 17, 33]])

In [49]:
# <<차원 축소 연산 - mean(), median(), np.all(), np.any()>>

x = np.array([1, 2, 3, 1])

In [43]:
# mean() : 평균
x.mean()

1.75

In [44]:
# median() : 중앙값
np.median(x)

1.5

In [47]:
# np.all()은 배열 요소가 모두 True일 때 True를 반환합니다.
# (하나라도 False면 False입니다.)
np.all([True, True, False])

False

In [48]:
# np.any()는 배열 요소가 하나라도 True면 True를 반환합니다.
# (전부 False면 False입니다.)
np.any([True, True, False])

True

In [53]:
# <<차원 축소 연산 - np.any(), np.all()>>
# np.any()의 요소가 단 하나라도 True이면 True를, 모두 False일 때는 False를 반환합니다.

# np.all()은 모든 요소가 True이면 True를, 하나라도 False일 때는 False를 반환합니다.

a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [54]:
((a <= b) & (b <= c)).all()

True

In [59]:
# 100 x 100 행렬 안에 다 0일 때

a = np.zeros((100, 100), dtype=np.int64)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [60]:
np.any(a != 0)  # a 가 0이 아니다?!

False

In [61]:
np.all(a == a) 

True

In [62]:
# 연습문제

practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2], 
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])


In [73]:
# 1. 전체의 최대값

practice.max()

9.0

In [74]:
# 2. 행 간의 합

practice.sum(axis = 0)

array([20.1, 27. , 23.6, 26. , 28.2, 26.5])

In [75]:
# 3. 행 간의 최대값

practice.max(axis = 0)

array([8.2, 8.8, 8. , 9. , 7.7, 8.9])

In [76]:
# 4. 열 간의 평균

practice.mean(axis = 1)

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [77]:
# 5. 열 간의 최소값
practice.min(axis = 1)

array([1.1, 2.7, 0.7, 0.2, 2.7])

In [78]:
# 정렬



In [82]:
# 만약 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort 명령을 사용합니다.

a = np.array([42, 38, 12, 25])   # 오름차순으로 인덱스 가져온 것
j = np.argsort(a)   # 순서대로 인덱스 가져온 것
j   # [42]=0, [38]=1, [12]=2, [25]=3

array([2, 3, 1, 0], dtype=int64)

In [83]:
a[j]

array([12, 25, 38, 42])

In [84]:
np.sort(a)

array([12, 25, 38, 42])

In [85]:
# 고급 인덱싱 - 인덱스 배열을 사용한 인덱싱

a = np.array([[1,2],[3,4],[5,6]])
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
print(a[[0,1,2], [0,1,0]])

[1 4 5]


In [90]:
# 강사님 추가설명

a = np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
a[[0,1,2], [0,1,0]]   # 1행의 1열, 2행의 2열, 3행의 1열

array([1, 4, 5])

In [93]:
# 슬라이싱 범위도 결국 인덱스 배열이라고 생각하면 됩니다.

a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
print(a[:, [0,1,0]]) # 전체(0,1,2)행에 대해서 [0,1,0] 범위를 갖는거
# 1행의 [0,1,0]
# 2행의 [0,1,0]
# 3행의 [0,1,0]

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [98]:
a[::-1, [0,1,0]]

array([[5, 6, 5],
       [3, 4, 3],
       [1, 2, 1]])

In [106]:
# 연습 문제

scores = np.array([[1, 2, 3, 4], # 학번
                   [46, 99, 100, 71], # 영어
                   [81, 59, 90, 100]]) # 수학

scores


array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [107]:
en = np.argsort(scores[1,:])

en

array([0, 3, 1, 2], dtype=int64)

In [111]:
scores[:, en]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [112]:
# 기술통계
# 넘파이는 다음과 같은 데이터 집합에 대해 간단한 통계를 계산하는 함수를 제공. 
# 이러한 값들을 통틀어 기술 통계(descriptive statistics)라고 합니다.


In [ ]:
# 표본 평균
np.mean()

# 표본 분산
np.var()

# 표본 표준편차
np.std()

# 최대값
np.max()

# 최소값
np.min()

# 중앙값
np.median()

In [ ]:
# 사분위수
1사분위수는 25%
np.median() 중앙값은 2사분위 50

In [116]:
# 난수 발생과 카운팅

# 시드 설정하기


In [125]:
# 시드 설정하기

np.random.seed(0)

In [126]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [127]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [128]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [135]:
# 시드 재설정
np.random.seed(0)

In [136]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [137]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [138]:
np.random.rand(10) 
# 시드 한번만 설정하면 랜덤이어도 똑같은 수가 나온다.
# 랜덤도 같아

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [141]:
# 데이터의 순서 바꾸기
# shuffle 함수 
# shuffle 함수도 자체 변환(in-place) 함수로 한 번 사용하면 변수의 값이 바뀝니다. 사용에 주의해야 합니다

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.random.shuffle(x)
x

array([3, 6, 1, 8, 5, 0, 9, 4, 7, 2])

In [144]:
# 데이터 샘플링
# choice 함수 사용

# choice 함수는 다음과 같은 인수를 가질 수 있습니다.
# numpy.random.choice(a, size=None, replace=True, p=None)

# ● a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
# ● size : 정수. 샘플 숫자.
# ● replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능.
# ● p : 배열. 각 데이터가 선택될 수 있는 확률

In [148]:
np.random.choice(5, 5, replace=False) # shuffle 명령과 같음.
                        # 5개 만들고 5개 뽑았는데 랜덤하게 뽑았으니까

array([0, 3, 2, 4, 1])

In [149]:
np.random.choice(5, 3, replace=False)

array([0, 1, 4])

In [151]:
np.random.choice(5, 10) # 반복해서 10개 선택

array([3, 4, 4, 4, 0, 4, 3, 2, 0, 1])

In [152]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) 
                        # 선택 확률을 다르게 해서 10개

array([3, 3, 3, 0, 3, 3, 3, 3, 3, 0])

In [ ]:
# 난수 생성

넘파이의 random 서브패키지는 이외에도 난수를 생성하는 다양한 함수를 제공합니다. 그 
중 가장 간단하고 많이 사용되는 것은 다음 3가지 함수입니다.
● rand: 0부터 1사이의 균일 분포
● randn: 표준 정규 분포
● randint: 균일 분포의 정수 난수


In [156]:
# 난수 생성

np.random.rand(10)  # 1차원

array([0.36980809, 0.14644176, 0.56961841, 0.70373728, 0.28847644,
       0.43328806, 0.75610669, 0.39609828, 0.89603839, 0.63892108])

In [161]:
np.random.rand(3, 5) # 2차원 ; 3 x 5행렬

array([[0.33898512, 0.17949026, 0.1709866 , 0.46345098, 0.87457296],
       [0.94411975, 0.60825287, 0.59665541, 0.78364425, 0.5000263 ],
       [0.05037006, 0.69909807, 0.9923964 , 0.26726254, 0.67909062]])

In [159]:
# randn 함수는 기댓값(mean)이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성합니다. 
# 인수 사용법은 rand 명령과 같습니다.

np.random.randn(10)

array([-0.25579069, -0.71438561, -0.50083877,  0.05564534, -0.48896178,
       -0.37992245,  0.25973465, -1.68134864, -0.91679481, -0.1192241 ])

In [160]:
np.random.randn(3, 5)

array([[-0.44627728, -2.14335544,  0.01003777, -0.55822259,  0.48090565],
       [-0.57414201, -0.2524676 ,  1.03984679, -0.02347953,  0.08942229],
       [-0.59432737, -0.10569679,  0.74279571, -0.75498153, -0.13828271]])

In [ ]:
randint 함수는 다음과 같은 인수를 가집니다.
numpy.random.randint(low, high=None, size=None)
만약 high를 입력하지 않으면 0과 low사이의 숫자를, high를 입력하면 low와 high는 
사이의 숫자를 출력합니다. 
size는 난수의 개수입니다.
high의 범위는 포함하지 않습니다.

In [164]:
np.random.randint(10, size = 10)
                # row만 썼어 그럼 0과 low사이의 숫자만

array([2, 5, 7, 7, 6, 1, 6, 7, 2, 3])

In [165]:
np.random.randint(10, 20, size = 10)


array([11, 19, 15, 19, 19, 12, 10, 19, 11, 19])

In [166]:
np.random.randint(10, 20, size = (3, 5))


array([[10, 16, 10, 14, 18],
       [14, 13, 13, 18, 18],
       [17, 10, 13, 18, 17]])

In [173]:
# 연습 문제

np.random.seed(0)

In [174]:
a = np.random.randint(0, 2, size = 100)

In [175]:
np.mean(a)

0.56

In [180]:
# 기영님
np.random.seed(0)
k = [np.random.randint(0, 2) for _ in range(100) ]
np.mean(k)

0.56

In [181]:
# 강사님
np.random.seed(0)
res = np.random.randint(0, 2, 100)
res.sum() / len(res)
  # 앞면의 개수 / 길이

0.56