In [1]:
# NumPy
# 넘파이 배열

import numpy as np
# anaconda에 기본적으로 포함되어 설치된 라이브러리

In [351]:
! conda list
# 넘파이 있는거 확인

# packages in environment at C:\Users\user\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.1            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0     

In [18]:
# 1차원 배열 만들기
# 넘파이(np)

ar = np.array([ _ for _ in range(10)])
# ndarray class로부터 객체를 생성한다.

In [3]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# np.array()로 생성한 객체는 numpy.ndarray 타입을 갖는다. (리스트가 아니져)
type(ar)

numpy.ndarray

In [17]:
# type(ar) 이 객체가 갖는 속성이 뭔지 확인
ar.shape

# (10,) -> 1차원의 10칸 갖는 ndarray

(10,)

In [10]:
ar2 = np.array([0.1, 12, 50, 2, 3.14])
ar2

# 정수<실수 / 정수*실수 = 실수 / 여기서도 똑같음
# 실수의 표현범위가 훨씬 넓어서 
# 하나의 자료형으로 표현할 때 큰 자료형으로 변환

array([ 0.1 , 12.  , 50.  ,  2.  ,  3.14])

In [11]:
x = np.array([1, 2, 3], dtype = 'f' )

In [12]:
x.dtype

dtype('float32')

In [13]:
np.array([1, 2, 3]).dtype

dtype('int32')

In [15]:
# ndarray도 인덱싱을 할 수 있다.
x[0] + x[1]

3.0

In [19]:
x = np.array([1, 2, 3], dtype = 'U' )

In [20]:
x

array(['1', '2', '3'], dtype='<U1')

In [22]:
x.dtype

# 메모리에 제일 효율적인 1칸짜리로 만들 수 있다는거. 최대.

dtype('<U1')

In [23]:
x[0] + x[1]

'12'

In [25]:
x = [0, 1, -1, 0]
y = [1, 0, 0 ,0]
x / y

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [26]:
xn = np.array(x)
yn = np.array(y)

In [27]:
xn

array([ 0,  1, -1,  0])

In [30]:
yn

array([1, 0, 0, 0])

In [32]:
xn / yn

# 0/1 은 0 인데 1/0 은? inf 무한대라는 수학적 표현
# -1/0 은 -방향으로 무한대 (-inf)
# 0/0 은 알 수가 없으므로 nan

C:\Users\user\AppData\Local\Temp\ipykernel_25160\2974482983.py:1: RuntimeWarning: divide by zero encountered in true_divide
  xn / yn
C:\Users\user\AppData\Local\Temp\ipykernel_25160\2974482983.py:1: RuntimeWarning: invalid value encountered in true_divide
  xn / yn


array([  0.,  inf, -inf,  nan])

In [36]:
[ _ for _ in range(10)] * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
[ _* 2 for _ in range(10)] 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [38]:
# 벡터화 연산

data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
answer = [ _* 2 for _ in range(10)] 

In [40]:
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [43]:
# 벡터화 연산
# 넘파이 배열 객체의 벡터화 연산을 사용하면 다음과 같이 for 반복문이 없이 간단하게 
# 단 한번의 연산식으로 표현할 수 있습니다. 물론 계산 속도도 리스트 객체에 반복문을 
# 사용해서 처리하는 것보다 훨씬 빠릅니다.

x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
# 앞서 학습했던 내용으로 파이썬 리스트 객체에 정수를 곱하면(*) 객체의 크기가 곱한 
# 숫자만큼 반복 증가합니다. 넘파이 배열 객체는 벡터화 연산이 이뤄진다고 바로 앞에서 
# 설명 드렸습니다. 이 차이점을 분명히 기억해둬야 합니다

list_samp = [_ for _ in range(3)]
print(list_samp * 5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [48]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [49]:
2 * a + b

array([12, 24, 36])

In [50]:
a = [1, 2, 3]
b = [10, 20, 30]

In [51]:
2 * a 

[1, 2, 3, 1, 2, 3]

In [53]:
2 * a + b

# 그냥 2*a 에서 b 리스트가 합쳐지지

[1, 2, 3, 1, 2, 3, 10, 20, 30]

In [57]:
# 리스트와 ndarray 연산 결과값이 다르지

an = np.array(a)
bn = np.array(b)

In [58]:
2 * an

array([2, 4, 6])

In [59]:
2 * an + b

array([12, 24, 36])

In [114]:
2 * an + bn

array([12, 24, 36])

In [61]:
True == 1 

True

In [62]:
False == 0

True

In [63]:
an

array([1, 2, 3])

In [64]:
bn

array([10, 20, 30])

In [65]:
an == 2

array([False,  True, False])

In [66]:
bn > 10

array([False,  True,  True])

In [67]:
(an ==2) & (bn > 10)

array([False,  True, False])

In [69]:
(an ==2) and (bn > 10)
# 넘파이에선 &로 해야해

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [71]:
an == 2 & bn > 10
# 왜 오류나? &의 우선순위 때문에! 꼭 소괄호 써야해

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [72]:
(an == 2) & (bn > 10)

array([False,  True, False])

In [74]:
# 2차원 배열 만들기 / 리스트 안에 리스트

c = np.array([[0, 1, 2], 
              [3, 4, 5]])   # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
c.shape   # 2행 3열 행렬

(2, 3)

In [79]:
# 행의 갯수
len(c) # 젤 껍데기

2

In [80]:
# 열의 갯수
len(c[0]) # 안에 있는 하나의 요소

3

In [83]:
# 연습 문제

ex = np.array([[10, 20, 30, 40],
               [50, 60, 70, 80]])
ex

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [86]:
# 3차원 배열 만들기
# 2 x 3 x 4
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])

In [87]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [88]:
d.dtype

dtype('int32')

In [89]:
d.shape

(2, 3, 4)

In [90]:
len(d)

2

In [91]:
len(d[0])

3

In [92]:
len(d[0][0])

4

In [94]:
len(d), len(d[0]), len(d[0][0])  # => tuple !!소괄호()생략된거

(2, 3, 4)

In [103]:
# 배열의 차원과 크기 알아내기
# ndim 속성 : 배열의 차원 반환
# shape 속성 : 배열의 크기 반환

a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [101]:
c = np.array([[0, 1, 2],
            [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [102]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [107]:
# 배열의 인덱싱

a = np.array([0, 1, 2, 3, 4])

In [108]:
a[2]

2

In [109]:
a[-1]

4

In [112]:
# list
test = [[1, 2, 3, 4], 
        [5, 6, 7, 8]]

In [113]:
test[1][-3]

6

In [115]:
test[1][1]

6

In [116]:
# 배열의 인덱싱
a = np.array([[0, 1, 2],
              [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
a. shape

(2, 3)

In [124]:
a.ndim

2

In [117]:
a[0, 0] # 첫번재 행의 첫번째 열

0

In [121]:
a[0, 1] # 첫번재 행의 두번째 열

1

In [122]:
a[-1, -1] # 마지막 행의 마지막 열

5

In [126]:
a[-1, 0] # 마지막 행의 첫번째 열

3

In [151]:
# cf. lisrt 슬라이싱
a = [[0, 1, 2, 3], [4, 5, 6, 7]] # a에서 0,1,2의 값을 가져오기

In [152]:
a[0][0:3]

[0, 1, 2]

In [153]:
a[0][:3]

[0, 1, 2]

In [154]:
# 배열의 슬라이싱

a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [155]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [156]:
a[:, 1] # 두번재 열 전체

array([1, 5])

In [157]:
a[1, 1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [158]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [159]:
# 연습 문제

m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [160]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [188]:
# 1
m[1, 2]

7

In [181]:
# 2
m[2,-1]

14

In [187]:
# 3
m[1,1:3]

array([6, 7])

In [186]:
# 4
m[1:, 2]

array([ 7, 12])

In [179]:
# 5
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [193]:
# 만약 [[3,4],[8,9],[13,14]] 슬라이싱 하고싶으면

m[:, 3:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

In [194]:
# 배열 생성

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [195]:
a.dtype

dtype('float64')

In [196]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [197]:
c.dtype

dtype('int32')

In [198]:
c.shape

(5, 2)

In [199]:
# 배열 생성
# zeros 메서드로 문자열 배열도 생성 가능하지만 
# 모든 요소의 문자열 크기가 같아야 합니다. 
# 만약 더 큰 크기의 문자열을 할당하면 잘릴 수 있습니다.

d = np.zeros(5, dtype = "U4")  # U4 ;길이 4까지로 제한둔거
d

array(['', '', '', '', ''], dtype='<U4')

In [202]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"   # 잘림
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [203]:
# 0이 아닌 1로 초기화된 배열을 생성하려면 ones 명령을 사용합니다.

e = np.ones((2, 3, 4), dtype = "i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [204]:
np.ones((2, 3, 4)).dtype

dtype('float64')

In [205]:
np.ones((2, 3, 4), dtype="U4")

array([[['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']],

       [['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']]], dtype='<U4')

In [206]:
# ex

test = np.array([10, 20, 22])

In [207]:
np.ones_like(test, dtype = "f")

array([1., 1., 1.], dtype=float32)

In [208]:
np.zeros_like(test, dtype = "f")

array([0., 0., 0.], dtype=float32)

In [209]:
np.zeros_like(test, dtype = "U10")

array(['', '', ''], dtype='<U10')

In [213]:
# 배열 생성 
# arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있습니다. 
# 특정한 규칙에 따라 증가하는 수열을 만듭니다.

np.arange(10)  # 0... n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
np.arange(3, 21, 2)   # 시작, 끝(포함x), 증감크기)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [218]:
# linspace : 선형 구간을 지정한 구간의 수만큼 분할함.

ex = np.linspace(0, 100, 5)
ex

array([  0.,  25.,  50.,  75., 100.])

In [219]:
# logspace : 로그 구간을 지정한 구간의 수만큼 분할함.


ex2 = np.logspace(0, 100, 5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [222]:
# 전치 연산
# 2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업입니다. 
# 이는 배열의 T 속성으로 구할 수 있습니다. 
# 메서드가 아닌 T속성이라는 점에 유의합니다

A = np.array([[1, 2, 3], [4, 5, 6]])
A    # 2 x 3 배열

array([[1, 2, 3],
       [4, 5, 6]])

In [223]:
A.T   # 3 x 2 배열

array([[1, 4],
       [2, 5],
       [3, 6]])

In [224]:
# 배열의 크기 변형

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [227]:
a.shape

(12,)

In [228]:
a.ndim

1

In [225]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [226]:
b.shape

(3, 4)

In [229]:
b.ndim

2

In [230]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [231]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [234]:
a.reshape(2, 2, -1).shape

(2, 2, 3)

In [232]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [233]:
a.reshape(2, -1, 2).shape

(2, 3, 2)

In [236]:
a.reshape(7, -1) # 나눠떨어지는 숫자로 원래 길이의 shape을 맞춰줘야한다.

ValueError: cannot reshape array of size 12 into shape (7,newaxis)

In [239]:
# 배열의 크기 변형
# 다차원 배열을 1차원으로 만들기 위해서는 flatten 혹은 ravel 메서드를 사용

a.reshape(2, 2, -1).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [240]:
a.reshape(2, 2, -1).flatten().shape

(12,)

In [241]:
a.reshape(2, 2, -1).ravel().shape

(12,)

In [247]:
# ex)강사님 예제

x = np.arange(5)

In [243]:
id(x)

2387325237744

In [244]:
x = np.arange(1, 5)

In [245]:
id(x)

2387325237264

In [246]:
x = np.arange(5, 1)
id(x)

2387325238320

In [250]:
# 배열의 크기 변형
# 이렇게 같은 배열에 대해 차원만 1차원 증가시키는 경우에는 
# newaxis 명령을 사용하기도 합니다

x = np.arange(5)

In [251]:
x

array([0, 1, 2, 3, 4])

In [252]:
x[:, np.newaxis]  # 새로운 차원을 추가시킨 것

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
# 배열 연결
# 행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하여(concatenate) 
# 더 큰 배열을 만들 때는 다음과 같은 명령을 사용
 ● hstack
● vstack
● dstack
● stack
● r_
● c_
● tile
● hstack

In [260]:
# hstack

a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [254]:
a2 = np.zeros((2, 3))
a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [256]:
np.hstack([a1, a2])    # 행의 수가 맞으니까 수평하게 합쳐주는거 

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [257]:
# vstack 열의 수가 같으니까 위아래로 합쳐

b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [258]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [259]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [264]:
np.hstack([a2, b1])    # 행의 수가 맞으니까 수평하게 합쳐주는거 

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
# dstack 명령은 제3의 축 즉, 행이나 열이 아닌 
# 깊이(depth) 방향으로 배열을 합칩니다.

In [265]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [266]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [267]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [268]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [269]:
c3 = np.empty((3, 4))

In [271]:
np.dstack([c1, c2, c3])

array([[[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]],

       [[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]],

       [[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]]])

In [270]:
np.dstack([c1, c2, c3]).shape

(3, 4, 3)

In [272]:
# 배열 연결
# 다음 예에서는 axis=0 이므로 가장 바깥에 값이 2인 차원이 추가됩니다. 
# 즉, shape 변화는 2개의 (3 x 4) -> 1개의 (2 x 3 x 4) 입니다

c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [277]:
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [278]:
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [279]:
c3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [276]:
c = np.dstack([c1, c2, c3])
c

array([[[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]],

       [[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]],

       [[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]]])

In [281]:
c = np.stack([c1, c2], axis = 0)
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [284]:
c.shape

(3, 4, 2)

In [282]:
c = np.stack([c1, c2], axis = 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [285]:
c.shape

(3, 4, 2)

In [287]:
c = np.stack([c1, c2], axis = 2)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [288]:
c.shape

(3, 4, 2)

In [292]:
# 오전 stack 복습

d1 = np.ones((4, 5))
d2 = np.zeros((4, 5))
d3 = np.arange(20).reshape(4,5)

In [293]:
d1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [294]:
d2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [295]:
d3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [296]:
np.stack([d1, d2, d3])  # 기본적으로 stack 은 각각 요소들이 합쳐진것

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [298]:
np.stack([d1, d2, d3], axis = 0)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [299]:
np.stack([d1, d2, d3], axis = 1)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [10., 11., 12., 13., 14.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [15., 16., 17., 18., 19.]]])

In [301]:
np.stack([d1, d2, d3], axis = 1).shape  # 3자리에서 합쳐졌지 axis가 1이니까

(4, 3, 5)

In [302]:
np.stack([d1, d2, d3], axis = 2)

array([[[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 1.,  0.,  2.],
        [ 1.,  0.,  3.],
        [ 1.,  0.,  4.]],

       [[ 1.,  0.,  5.],
        [ 1.,  0.,  6.],
        [ 1.,  0.,  7.],
        [ 1.,  0.,  8.],
        [ 1.,  0.,  9.]],

       [[ 1.,  0., 10.],
        [ 1.,  0., 11.],
        [ 1.,  0., 12.],
        [ 1.,  0., 13.],
        [ 1.,  0., 14.]],

       [[ 1.,  0., 15.],
        [ 1.,  0., 16.],
        [ 1.,  0., 17.],
        [ 1.,  0., 18.],
        [ 1.,  0., 19.]]])

In [303]:
np.stack([d1, d2, d3], axis = 2).shape

(4, 5, 3)

In [307]:
# 배열 연결
# r_ 메서드는 hsstack 명령과 비슷하게 배열을 좌우로 연결.

np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

# hstack([])과 차이가 없다.
# r_ 얘는 [] 대괄호로만! 이런 특수 메서드를 인덱서라고 함.

array([1, 2, 3, 4, 5, 6])

In [310]:
# c_메서드 

np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [312]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [313]:
np.tile(a,3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [314]:
np.tile(a, (4, 3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [315]:
# tile 명령 : 동일한 배열을 반복하여 연결 / 메모 사진

a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [333]:
np.tile(a, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [327]:
# 연습 문제

a1 = np.zeros([3, 3])
b1 = np.ones([3, 2])

In [328]:
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [334]:
a1.shape

(3, 3)

In [329]:
b1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [335]:
b1.shape

(3, 2)

In [330]:
c1 = np.arange(10, 160, 10).reshape(3, 5)

In [ ]:
c1

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [339]:
c1.shape

(3, 5)

In [340]:
d1 = np.hstack([a1, b1])

In [341]:
d1

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [345]:
e1 = np.vstack([d1, c1])

In [346]:
e1

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [348]:
np.tile(e1, (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [352]:
# 연습 문제

a = np.zeros([3, 3])
b = np.ones([3, 2])
c = np.arange(10, 160, 10).reshape(3, 5)
d = np.hstack([a, b])
e = np.vstack([d, c])
np.tile(e, (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [ ]:
# 풀이 중에  reshape(3,-1 ) 이거 이해 안감

In [ ]:
<벡터화 연산>
앞서 넘파이가 벡터화 연산(vectorized operation)을 지원한다고 했음.
벡터화 연산을 쓰면 명시적으로 반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복 
연산을 할 수 있음.
 벡터화 연산의 또다른 장점은 선형 대수 공식과 동일하게 아주 
간단한 파이썬 코드를 작성할 수 있다는 점.


In [41]:
import numpy as np

In [42]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [43]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 5.05 ms


In [44]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [45]:
# 벡터화 연산
# 사칙 연산뿐 아니라 비교연산과 같은 논리 연산도 벡터화 연산이 가능하다.

a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [46]:
a == b

array([False,  True, False,  True])

In [47]:
a >= b

array([False,  True,  True,  True])

In [48]:
(a == b) & (a >= b)

array([False,  True, False,  True])

In [14]:
# 벡터화 연산
# 만약 배열의 각 원소들을 일일히 비교하는 것이 아니라 
# 배열의 모든 원소가 다 같은지 알고 싶다면 all 명령을 사용하면 됩니다
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [15]:
np.all(a == b)

False

In [16]:
np.all(a == c)

True

In [17]:
# 스칼라와 벡터/행렬의 곱셈
# 넘파이 배열에서 스칼라와 벡터/행렬의 곱도 
# 선형대수에서 사용하는 식과 같이 표현 가능

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [21]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [23]:
# 브로드캐스팅
# 보통 배열끼리 산술 연산을 하려면 아래의 예제처럼 
# 두 배열의의 shapes가 정확히 같아야 합니다

In [35]:
# 차원 축소 연산

In [36]:
# sum() 메서드

x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [37]:
np.sum(x)  # 넘파이의 sum

10

In [38]:
x.sum()  #np.array() 위하고 차이가 뭐야?

10

In [2]:
import numpy as np

In [3]:
# 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있습니다.

x = np.arrange(12).reshape(3, -1)    # 3 x 4 행렬로 만든거
x

AttributeError: module 'numpy' has no attribute 'arrange'

In [4]:
아니 왜자꾸 오류떰????

SyntaxError: invalid syntax (4081372745.py, line 1)